In [1]:
import cv2
import numpy as np
import random
import matplotlib.pyplot as plot

In [2]:
print(random.randint(0,9))

1


In [3]:
rw, cl = input("Enter the size of the image: ").split()
rw = int(rw)
cl = int(cl)
print(rw)
print(cl)

Enter the size of the image: 1000 500
1000
500


In [4]:
custom_image = np.random.randint(0, 255, (cl, rw, 3))
custom_image = custom_image.astype(float)
print(custom_image)
print(type(custom_image))

[[[ 32. 230. 108.]
  [ 30.  51. 120.]
  [ 40. 136.  25.]
  ...
  [196. 203.  27.]
  [245. 123. 171.]
  [172. 185. 245.]]

 [[191.  31. 241.]
  [217.  97.  99.]
  [ 45. 189. 150.]
  ...
  [137. 161. 251.]
  [210.  36.  80.]
  [ 87. 170. 177.]]

 [[  7. 189. 117.]
  [ 32. 155. 105.]
  [148. 123.  35.]
  ...
  [ 71. 167. 148.]
  [122.  41.  14.]
  [179.  52. 160.]]

 ...

 [[228.  57. 251.]
  [166. 212.  65.]
  [246.  22. 133.]
  ...
  [ 34.  46. 192.]
  [154. 227. 155.]
  [204.  56.  34.]]

 [[190. 132. 231.]
  [ 25.  54.   7.]
  [248.  47.  20.]
  ...
  [194. 220. 205.]
  [ 51. 101. 224.]
  [133. 185. 137.]]

 [[ 17.  26. 214.]
  [152. 250. 227.]
  [180. 236.  98.]
  ...
  [212. 217.  26.]
  [  6. 188. 178.]
  [215.  39. 193.]]]
<class 'numpy.ndarray'>


In [5]:
custom_image.shape

(500, 1000, 3)

In [ ]:
cv2.imshow("Custom Created Image", custom_image)
cv2.waitKey(0) == 13
cv2.destroyAllWindows()

In [ ]:
cv2.imwrite("CustomImage.jpg",custom_image)